// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nemesis.Models.Contexts;

#nullable disable

namespace nemesis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230518143122_SeedInvestigations")]
    partial class SeedInvestigations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "68a525ac-d446-4c8c-983c-047afdffed13",
                            ConcurrencyStamp = "df0d80eb-b0cb-4cf9-8b00-d65838b36096",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "fca95d41-370a-4218-b0aa-8502494448fb",
                            ConcurrencyStamp = "1feb194d-2c23-4205-9d30-9fa9a599f7fd",
                            Name = "Investigator",
                            NormalizedName = "INVESTIGATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fac97539-cb0b-4b9f-ae20-497eafb414bc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c447afe6-e53d-4f03-8f0d-745421fcd09a",
                            Email = "su@do.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SU@DO.COM",
                            NormalizedUserName = "SUDO",
                            PasswordHash = "AQAAAAEAACcQAAAAEMlv2qrGg1nrwO0T8qah9hd949VOHMytVvOisqDn1OCSMn2aZu2bpfVOUSCZ7Nb1VA==",
                            PhoneNumber = "0",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3ee3927c-a606-4977-ae7f-3988c7a976c3",
                            TwoFactorEnabled = false,
                            UserName = "Sudo"
                        },
                        new
                        {
                            Id = "92b32ccb-8835-4e2d-ae6c-8c86eb2efed6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2765bba9-9548-45b9-8e85-88d8d4f8fa5e",
                            Email = "cop2@mall.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "COP2@MALL.COM",
                            NormalizedUserName = "PAULBLART",
                            PasswordHash = "AQAAAAEAACcQAAAAEL6I1cEWjUDKWbcJIRe93Q5Rvxo9pP4JbK84yMyvCQ6fb5KDcJEp2us899088mvsKA==",
                            PhoneNumber = "911911",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb9a64c0-31aa-49e7-b6b7-5092ec8d5c03",
                            TwoFactorEnabled = false,
                            UserName = "PaulBlart"
                        },
                        new
                        {
                            Id = "9059e247-2854-40bd-af2b-76088f8dd4e6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c608a211-75da-4a2e-be27-852074847b0b",
                            Email = "gadget@inspect.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GADGET@INSPECT.COM",
                            NormalizedUserName = "INSPECTORGADGET",
                            PasswordHash = "AQAAAAEAACcQAAAAECdhLa5Jquu8vQbxcJYwT+9Zy1VbSZnBqVMT5wXax9ONbwGG4XMLFvnvuyBbpk87Qg==",
                            PhoneNumber = "23480922",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "14f07c36-d0f5-475b-b9ea-83d6d5abf2f3",
                            TwoFactorEnabled = false,
                            UserName = "InspectorGadget"
                        },
                        new
                        {
                            Id = "84b91c9f-74d1-452d-927b-439bfd3a7287",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3fbe9699-21d8-4835-82a2-6c84f5a2373b",
                            Email = "element@inspect.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ELEMENT@INSPECT.COM",
                            NormalizedUserName = "ELEMENT",
                            PasswordHash = "AQAAAAEAACcQAAAAEDFWB5RsiVHEy9/OrTY3chhQX0UFMDjPJhZZOGCY2jGGh/F0ocpgpPT9WkEqyZ3y7w==",
                            PhoneNumber = "(650) 253-0000",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cc54b66c-70ec-41d2-8abb-6d0de3e0532b",
                            TwoFactorEnabled = false,
                            UserName = "Element"
                        },
                        new
                        {
                            Id = "5888e361-c81f-4ac9-8e16-961b0eeed0ae",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c615f001-cb88-4c1b-af9c-2e63996ed40e",
                            Email = "cetta@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CETTA@HOTMAIL.COM",
                            NormalizedUserName = "CETTA",
                            PasswordHash = "AQAAAAEAACcQAAAAELyXNThJ26bYsg8a00kXmL4XGgQj2UIG3EejmPmpmDSWPn/reWEalg2AGgQ6mec3Sg==",
                            PhoneNumber = "21249200",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9c93ad05-fc42-40dc-8933-1737ef47d7b9",
                            TwoFactorEnabled = false,
                            UserName = "Cetta"
                        },
                        new
                        {
                            Id = "ad9a20a1-779e-4991-8881-9af6171668a5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9ac514b-e8bd-4a67-9989-ab07f443739f",
                            Email = "karen@qrid.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KAREN@QRID.COM",
                            NormalizedUserName = "KAREN",
                            PasswordHash = "AQAAAAEAACcQAAAAEAgIISXMPyIgsBQg+yylze47ldeRqCq0b4dT/F2lAJiM8FhUMEVWZ9i1/wE0BjS3hg==",
                            PhoneNumber = "10291029",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c988290c-1042-4404-900e-3bf86832d394",
                            TwoFactorEnabled = false,
                            UserName = "Karen"
                        },
                        new
                        {
                            Id = "555e52b8-22db-4c15-a037-107016c7f827",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd0c992d-e4b3-406c-a2f9-7757433f89c6",
                            Email = "CandiceFlynn@snitch.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CANDICEFLYNN@SNITCH.COM",
                            NormalizedUserName = "CANDICE",
                            PasswordHash = "AQAAAAEAACcQAAAAEDuhwbetdyOfZpIscOM47j3gxqRzQLidbsDS7I/YrQqoIHZnSPO60q4rKP96Y9WpaQ==",
                            PhoneNumber = "201920192",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a5b8ac06-1221-480d-b981-356182ca50ba",
                            TwoFactorEnabled = false,
                            UserName = "Candice"
                        },
                        new
                        {
                            Id = "5cefc46b-1918-4ae3-8a40-4d337ff9a670",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c5f9c41-7bcf-4d21-87e6-47d602c7948f",
                            Email = "head@snitch.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HEAD@SNITCH.COM",
                            NormalizedUserName = "6IX9INE",
                            PasswordHash = "AQAAAAEAACcQAAAAEBbxAsAwaKFI/gZZW6SAjlgZVZO5Uffa+M63kqOe2CjzY16tIdXrB6/gpc7MG9IJkA==",
                            PhoneNumber = "1231233412",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bf278899-1a0e-46b0-9edc-ded267ebf564",
                            TwoFactorEnabled = false,
                            UserName = "6ix9ine"
                        },
                        new
                        {
                            Id = "3303fdaf-f438-4582-8f10-52b578c50cb8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "46ad767f-432d-4670-9163-fe77ee72c294",
                            Email = "homework@reminder.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HOMEWORK@REMINDER.COM",
                            NormalizedUserName = "HOMEWORKREMINDER",
                            PasswordHash = "AQAAAAEAACcQAAAAEO85TAzyj8Yn1olCveaQYyi+aD96UcOGYlzmsMRoiy0UnSIeSWmfQouGJgKep3uq2Q==",
                            PhoneNumber = "123412521",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f94f13e4-2640-4c78-8965-59bd28426824",
                            TwoFactorEnabled = false,
                            UserName = "homeworkReminder"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "fac97539-cb0b-4b9f-ae20-497eafb414bc",
                            RoleId = "68a525ac-d446-4c8c-983c-047afdffed13"
                        },
                        new
                        {
                            UserId = "fac97539-cb0b-4b9f-ae20-497eafb414bc",
                            RoleId = "fca95d41-370a-4218-b0aa-8502494448fb"
                        },
                        new
                        {
                            UserId = "92b32ccb-8835-4e2d-ae6c-8c86eb2efed6",
                            RoleId = "fca95d41-370a-4218-b0aa-8502494448fb"
                        },
                        new
                        {
                            UserId = "9059e247-2854-40bd-af2b-76088f8dd4e6",
                            RoleId = "fca95d41-370a-4218-b0aa-8502494448fb"
                        },
                        new
                        {
                            UserId = "84b91c9f-74d1-452d-927b-439bfd3a7287",
                            RoleId = "fca95d41-370a-4218-b0aa-8502494448fb"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("nemesis.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Uncategorised"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Unsafe act"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Condition"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Equipment"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Structure"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Apocalyptic Event"
                        });
                });

            modelBuilder.Entity("nemesis.Models.Investigation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAction")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestigatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Investigations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfAction = new DateTime(2023, 5, 18, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(911),
                            Description = "All must hail Ahman'tuep, the majestic ancient volcano, she who rules over fiery peaks and molten lava with a ceaseless hunger Legend has it that to keep her volcanic wrath at bay, a staggering offering of ten thousand chicken nuggets must be laid at his divine feet each day As the heavens watch in awe, we puny mortals must scurry about, frying, seasoning, and presenting an endless bounty of crispy poultry goodness. Perhaps it is the secret blend of herbs and spices that infuses each nugget with just the right amount of flavor to calm his fiery cravings. Or maybe Ahman'tuep just really loves the combination of tender chicken and tantalizing dipping sauces. Either way, one thing is certain: if we want to keep a volcano from erupting, she must be fed!",
                            InvestigatorId = "84b91c9f-74d1-452d-927b-439bfd3a7287",
                            StatusId = 2
                        },
                        new
                        {
                            Id = 2,
                            DateOfAction = new DateTime(2023, 5, 18, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(913),
                            Description = "In the battle of the roadways, where rubber meets the asphalt, a case of wild wheelery unfolded this morning. Thankfully no one was 'flattened' in the incident! With 'tireless' dedication devoted to uncovering the enigma behind the truck  tyre's unexpected detachment. By analyzing the gathered surveillance footage, piecing together witness statements, and examining the evidence, we thankfully managed to unravel the mystery and bring justice to the asphalt.",
                            InvestigatorId = "9059e247-2854-40bd-af2b-76088f8dd4e6",
                            StatusId = 3
                        },
                        new
                        {
                            Id = 3,
                            DateOfAction = new DateTime(2023, 5, 18, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(914),
                            Description = "After much debate among the investigators, we have decided that no action is required as we must all learn to share the playground No, we did not receive an anonymous donation of thirteen million, five hundred and fourty thousand, three hundred and 26 euro and 43 cents to close this case. In fact, studies show that a daily exposure to ionized radiation is healthy for children! Think about how special little Billy with be with an extra hand! Have you never considered the convenience of such a mutation?!",
                            InvestigatorId = "afdb900f-344d-4bf7-9239-34a2ea4336be",
                            StatusId = 4
                        },
                        new
                        {
                            Id = 4,
                            DateOfAction = new DateTime(2023, 5, 18, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(969),
                            Description = "Solid copy, we went on site and socketed back in place, thank you for the report.",
                            InvestigatorId = "92b32ccb-8835-4e2d-ae6c-8c86eb2efed6",
                            StatusId = 3
                        },
                        new
                        {
                            Id = 5,
                            DateOfAction = new DateTime(2023, 5, 18, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(972),
                            Description = "One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us. One of us.",
                            InvestigatorId = "84b91c9f-74d1-452d-927b-439bfd3a7287",
                            StatusId = 4
                        },
                        new
                        {
                            Id = 6,
                            DateOfAction = new DateTime(2023, 5, 18, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(973),
                            Description = "Beware the coming terror as Cthulhu awakens! From the depths, an ancient cosmic horror emerges, heralding the end of all sanity and civilization. Prepare for unimaginable chaos, as madness spreads like wildfire and reality crumbles. The mere glimpse of Cthulhu's grotesque form will shatter the minds of those unfortunate enough to witness it. Brace for the impending doom, for the world as you know it shall be consumed by darkness and despair. Salvation is but a futile hope against the incomprehensible might of Cthulhu. Abandon all hope, for the age of humanity draws to a close, and the reign of the Great Old Ones begins anew.\r\n\r\nTHE END IS NIGH! THE END IS NIGH!",
                            InvestigatorId = "afdb900f-344d-4bf7-9239-34a2ea4336be",
                            StatusId = 4
                        },
                        new
                        {
                            Id = 7,
                            DateOfAction = new DateTime(2023, 5, 18, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(974),
                            Description = "Considering you were at Zeppi's, that was probably just the head rat-chef Remy, he may have fallen on hard times since his wife left him after the sequel to Ratatouille flopped, but that's no excuse to call him fat! Monster!",
                            InvestigatorId = "9059e247-2854-40bd-af2b-76088f8dd4e6",
                            StatusId = 3
                        },
                        new
                        {
                            Id = 8,
                            DateOfAction = new DateTime(2023, 5, 18, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(975),
                            Description = "THE BEAAAAAAAAAAAAAAANZ?!?! WHY WON'T ANYONE THINK OF THE CHILDREN! THE BEAAAAAAAAAAAAAAAANZZZZZ!!",
                            InvestigatorId = "afdb900f-344d-4bf7-9239-34a2ea4336be",
                            StatusId = 2
                        },
                        new
                        {
                            Id = 9,
                            DateOfAction = new DateTime(2023, 5, 18, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(976),
                            Description = "Preliminary reports indicate that the impostor prefers fidget spinners over Rubik's Cubes The impostor must be caught at all costs! All hands on deck!  ",
                            InvestigatorId = "84b91c9f-74d1-452d-927b-439bfd3a7287",
                            StatusId = 2
                        });
                });

            modelBuilder.Entity("nemesis.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfReport")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSpotted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvestigationId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StatusId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            CreatedByUserId = "555e52b8-22db-4c15-a037-107016c7f827",
                            DateOfReport = new DateTime(2023, 4, 30, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(854),
                            DateSpotted = new DateTime(2023, 4, 28, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(848),
                            Description = "I've recently discovered that the Maghtab garbage dump is actually an active volcano. Not only that, it's apparently sentient and has been constantly demanding tribute in the form of human sacrifice, will the authorities please do something about this before it loses its patience and destroys us all?!",
                            ImageUrl = "/images/SentientVolcano.jpg",
                            InvestigationId = 1,
                            Location = "Maghtab",
                            StatusId = 1,
                            Title = "Sentient volcano"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            CreatedByUserId = "ad9a20a1-779e-4991-8881-9af6171668a5",
                            DateOfReport = new DateTime(2023, 5, 6, 16, 55, 22, 311, DateTimeKind.Utc).AddTicks(859),
                            DateSpotted = new DateTime(2023, 5, 6, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(857),
                            Description = "Someone must be having a bad morning because as I was driving up to work, a truck tyre bounced off my dashboard and kept rolling down the road! I hope some unsuspecting jogger doesn't cross its path because then he'll definitely end up getting 'tyred'.",
                            ImageUrl = "/images/RunawayTyre.jpg",
                            InvestigationId = 2,
                            Location = "Birzebbugia",
                            StatusId = 1,
                            Title = "Runaway Tyre"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedByUserId = "ad9a20a1-779e-4991-8881-9af6171668a5",
                            DateOfReport = new DateTime(2023, 5, 7, 15, 43, 22, 311, DateTimeKind.Utc).AddTicks(861),
                            DateSpotted = new DateTime(2023, 5, 7, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(861),
                            Description = "Just this evening I took the kids to the children's playground and was shocked when I noticed that one of them had grown an extra appendage! Apparently while I was chatting with the other parents, the kids had found a barrel of radioactive waste hidden in a small room underneath the playground and were making sand castles out of the stuff!",
                            ImageUrl = "/images/RadioactiveBarrel.jpg",
                            InvestigationId = 3,
                            Location = "Hal-Qormi",
                            StatusId = 1,
                            Title = "Radioactive Barrels"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedByUserId = "ad9a20a1-779e-4991-8881-9af6171668a5",
                            DateOfReport = new DateTime(2023, 5, 13, 16, 55, 22, 311, DateTimeKind.Utc).AddTicks(863),
                            DateSpotted = new DateTime(2023, 5, 13, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(863),
                            Description = "There is a missing manhole cover on the highway just outside of Cikku bar, I think the storm last night dislodged it and now it's posing a danger to anyone driving through that road. I hope it gets investigated before someone gets hurt!",
                            ImageUrl = "/images/Manhole.jpg",
                            InvestigationId = 4,
                            Location = "Haz-Zebbug",
                            StatusId = 1,
                            Title = "Missing manhole cover"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedByUserId = "afdb900f-344d-4bf7-9239-34a2e",
                            DateOfReport = new DateTime(2023, 5, 16, 16, 55, 22, 311, DateTimeKind.Utc).AddTicks(865),
                            DateSpotted = new DateTime(2023, 5, 16, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(864),
                            Description = "I heard some commotion last night but thought it was just the local gang of racoons as usual so I slept through it. This morning, I find that a meteor containing alien worms had crash landed in my backyard! At first I came out with my trusty broomstick but it turns out they're incredibly friendly! I assure you they absolutely have not infiltrated my brain, and are definitely not forcing me to write this. By the way everyone should come see for themselves as soon as possible, the Hivemind demands it.",
                            ImageUrl = "/images/Meteor.jpg",
                            InvestigationId = 5,
                            Location = "Siggiewi",
                            StatusId = 1,
                            Title = "Meteor in my backyard"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CreatedByUserId = "afdb900f-344d-4bf7-9239-34a2e",
                            DateOfReport = new DateTime(2023, 5, 15, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(867),
                            DateSpotted = new DateTime(2023, 5, 15, 2, 31, 22, 311, DateTimeKind.Utc).AddTicks(867),
                            Description = "I was taking a lovely stroll on the beach last night when suddenly, my partner noted that the ancient old god Cthulhu had manifested out of the sea, heralding the end of days for humanity and all life as we know it!",
                            ImageUrl = "/images/Cthulhu.jpg",
                            InvestigationId = 6,
                            Location = "Ghar Lapsi",
                            StatusId = 1,
                            Title = "Old God rises from the depths"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedByUserId = "5888e361-c81f-4ac9-8e16-961b0eeed0ae",
                            DateOfReport = new DateTime(2023, 5, 16, 4, 55, 22, 311, DateTimeKind.Utc).AddTicks(870),
                            DateSpotted = new DateTime(2023, 5, 16, 2, 31, 22, 311, DateTimeKind.Utc).AddTicks(869),
                            Description = "We were having lunch at Zeppi's Diner last night when suddenly, a rodent the size of a car scurried out of the kitchen! I have to say it really put us off finishing the meal. I hope the food safety authorities see this post!",
                            ImageUrl = "/images/GiantRodent.png",
                            Location = "Hamrun",
                            StatusId = 1,
                            Title = "Giant rodent"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedByUserId = "ad9a20a1-779e-4991-8881-9af6171668a5",
                            DateOfReport = new DateTime(2023, 5, 16, 16, 55, 22, 311, DateTimeKind.Utc).AddTicks(872),
                            DateSpotted = new DateTime(2023, 5, 16, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(871),
                            Description = "We went out for dinner at Fonzu's last night and were having a great time! Hats off to the guy who was playing the accordion with his feet. I ordered the special 'Fonzu's Burger' off the menu, and, to say the least, was shocked when the waitress brought it to the table. It was just a clump of greasy hair! I don't know who thought this was a good idea or how it passed any form of review! Talk about finding a hair in the food! ",
                            ImageUrl = "/images/HairBurger.jpeg",
                            InvestigationId = 7,
                            Location = "Naxxar",
                            StatusId = 1,
                            Title = "Hairy Burger"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedByUserId = "5cefc46b-1918-4ae3-8a40-4d337ff9a670",
                            DateOfReport = new DateTime(2023, 5, 17, 2, 31, 22, 311, DateTimeKind.Utc).AddTicks(874),
                            DateSpotted = new DateTime(2023, 5, 16, 21, 43, 22, 311, DateTimeKind.Utc).AddTicks(873),
                            Description = "I was out shopping with the kids when we came across a passed out man in the middle of the sidewalk. Normally I wouldn't post something like this, because let's face it, we've all been there. However, what really bothered me was that he was snoring so loud it sounded like an entire trombone orchestra! Simply unacceptable!",
                            ImageUrl = "/images/ManPassedOut.jpg",
                            Location = "Bormla",
                            StatusId = 1,
                            Title = "Passed out man"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            CreatedByUserId = "afdb900f-344d-4bf7-9239-34a2e",
                            DateOfReport = new DateTime(2023, 5, 17, 19, 19, 22, 311, DateTimeKind.Utc).AddTicks(875),
                            DateSpotted = new DateTime(2023, 5, 17, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(875),
                            Description = "HOW IS THIS ACCEPTABLE!? MY FAVOURITE HEINZ BAKED BEANZ HAVE BEEN OUT OF STOCK FOR THE LAST 2 DAYS!??!1?111? HOW AM I SUPPOSED TO FEED MY CHILDREN A NUTRITIOUS BREAKFAST IF I DON'T HAVE ANY BEANZ! WHY AREN'T THERE ANY BEANZ!?!11?",
                            ImageUrl = "/images/MissingBeans.webp",
                            InvestigationId = 8,
                            Location = "Mosta",
                            StatusId = 1,
                            Title = "MISSING BEANZ"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedByUserId = "5888e361-c81f-4ac9-8e16-961b0eeed0ae",
                            DateOfReport = new DateTime(2023, 5, 18, 7, 19, 22, 311, DateTimeKind.Utc).AddTicks(877),
                            DateSpotted = new DateTime(2023, 5, 18, 2, 31, 22, 311, DateTimeKind.Utc).AddTicks(877),
                            Description = "Like most of you, I buy my toilet paper from the gas station. I was disgusted this morning when some --redacted-- bought out the entire shop! Does this guy have ten --redacted--!? How am I supposed to wipe my --redacted-- without any toilet paper?!",
                            ImageUrl = "/images/ToiletPaperHoarder.jpg",
                            Location = "Mosta",
                            StatusId = 1,
                            Title = "Toilet Paper Hoarder"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CreatedByUserId = "84b91c9f-74d1-452d-927b-439bfd3a7287",
                            DateOfReport = new DateTime(2023, 5, 18, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(879),
                            DateSpotted = new DateTime(2023, 5, 17, 14, 31, 22, 311, DateTimeKind.Utc).AddTicks(878),
                            Description = "Imposter detected!!!!!!\n This van tried to impersonate Dr Chris Porter (PhD, MD, JD, MBA, MS, MFA, DSc, DPhil, DEd, DPT, DVM, DSW, DMus, DEng, DM, DNurs, DLit, DDS, DClinPsy, DPharm, DArch, and DBA), the erudite, brilliant, innovative, charismatic, awe-inspiring, compassionate, visionary, and unparalleled intellectual powerhouse, whose prodigious knowledge, remarkable expertise, and boundless passion for teaching have transformed countless minds and left an indelible mark on the realm of academia.\n\nps: chatgpt is really useful",
                            ImageUrl = "/images/Porter.jpg",
                            InvestigationId = 9,
                            Location = "London",
                            StatusId = 1,
                            Title = "Porter imposter"
                        });
                });

            modelBuilder.Entity("nemesis.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Open"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Being Investigated"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Closed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "No Action Required"
                        });
                });

            modelBuilder.Entity("nemesis.Models.Upvote", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.Property<int?>("ReportViewModelId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ReportID");

                    b.HasIndex("ReportID");

                    b.HasIndex("ReportViewModelId");

                    b.HasIndex("UserId", "ReportID")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("UserId", "ReportID"), false);

                    b.ToTable("Upvotes");
                });

            modelBuilder.Entity("nemesis.ViewModels.CategoryViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryViewModel");
                });

            modelBuilder.Entity("nemesis.ViewModels.ReportViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfReport")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSpotted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvestigationId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StatusId");

                    b.ToTable("ReportViewModel");
                });

            modelBuilder.Entity("nemesis.ViewModels.StatusViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusViewModel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("nemesis.Models.Investigation", b =>
                {
                    b.HasOne("nemesis.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("nemesis.Models.Report", b =>
                {
                    b.HasOne("nemesis.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nemesis.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("nemesis.Models.Upvote", b =>
                {
                    b.HasOne("nemesis.Models.Report", "Report")
                        .WithMany("Upvotes")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nemesis.ViewModels.ReportViewModel", null)
                        .WithMany("Upvotes")
                        .HasForeignKey("ReportViewModelId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("nemesis.ViewModels.ReportViewModel", b =>
                {
                    b.HasOne("nemesis.ViewModels.CategoryViewModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("nemesis.ViewModels.StatusViewModel", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("nemesis.Models.Report", b =>
                {
                    b.Navigation("Upvotes");
                });

            modelBuilder.Entity("nemesis.ViewModels.ReportViewModel", b =>
                {
                    b.Navigation("Upvotes");
                });
#pragma warning restore 612, 618
        }
    }
}
